Resources:
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: "etraining-frontend-bucket"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: "arn:aws:s3:::etraining-frontend-bucket/*"

Outputs:
  WebsiteURL:
    Value: "http://etraining-frontend-bucket.s3-website-sa-east-1.amazonaws.com"
    Description: URL for the website hosted on S3
